import { Button } from "@/components/ui/button";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/fonts/GeistSans-Regular.woff2" as="font" crossOrigin="anonymous" />
      </Head>
      <div>
        <main>
          <h1>index</h1>
          <Link href="/blog">Blog</Link>
          <Button asChild>
            <Link href="/blog">Go to Blog</Link>
          </Button>
          <Button asChild>
            <Link href="/dashboard/">Go to dasdoad</Link>
          </Button>
        </main>
      </div>
    </>
  );
}
