import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Dashboard() {
  return (
    <>
      {Array.from({ length: 10 }).map((_, i) => (
        <div
          key={i}
          className="aspect-video max-w-3xl rounded-xl bg-muted/50"
        />
      ))}
    </>
  )

}