import Head from "next/head";
import Link from "next/link";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/fonts/GeistSans-Regular.woff2" as="font" crossOrigin="anonymous" />
      </Head>
      <h1>Blog</h1>
      <Link href="/">Home</Link>
      <Link href="/blog/tin-tuc-0111">blog detail</Link>
    </>
  );
}